from pathlib import Path
root=Path('/mnt/data/v62work')
s=(root/'app-v61.js').read_text()
repls=[]
def rep(a,b,name):
 global s
 if a not in s: raise SystemExit('missing '+name)
 s=s.replace(a,b)
# 1 invoice + schedule tab
rep('const invoiced=(state.invoices||[]).reduce((a,x)=>a+Number(x.total_amount||0),0);\n const paid=(state.invoices||[]).filter(x=>x.status==="paid").reduce((a,x)=>a+Number(x.total_amount||0),0);','const invoiced=(state.invoices||[]).reduce((a,x)=>a+Number(x.total||0),0);\n const paid=(state.invoices||[]).filter(x=>x.status==="paid").reduce((a,x)=>a+Number(x.total||0),0);','invoice calc')
rep("[['overview','Overview'],['work','Work'],['financial','Financial'],['changes','Change Orders'],['invoices','Invoices'],['field','Field Updates'],['activity','Activity']]", "[['overview','Overview'],['work','Work'],['financial','Financial'],['schedule','Schedule'],['changes','Change Orders'],['invoices','Invoices'],['field','Field Updates'],['activity','Activity']]",'tabs')
# 2 field command + task stats before timePanel
needle=' const timePanel=fieldUser?`<div class="card" style="margin:12px 0"><div class="row"><div><b>Time</b>'
insert=''' const openTasks=tasks.filter(t=>t.status!=="complete");\n const doneTasks=tasks.length-openTasks.length;\n const taskPct=tasks.length?Math.round(doneTasks/tasks.length*100):0;\n const pendingMaterials=(state.materials||[]).filter(m=>{const st=String(m.status||"requested").toLowerCase();return st!=="fulfilled"&&st!=="complete";}).length;\n const reportCount=(state.reports||[]).filter(r=>r.job_id===j.id).length;\n const fieldCommand=fieldUser?`<section class="field-command card"><div class="eyebrow">FIELD COMMAND</div><div class="row" style="align-items:flex-start"><div><h2 style="margin:0">Today's Job Brief</h2><div class="sub">Stay on the work, keep the office in the loop.</div></div><span class="field-percent">${taskPct}%</span></div><div class="field-progress"><span style="width:${taskPct}%"></span></div><div class="field-command-grid"><div><b>${doneTasks}/${tasks.length}</b><span>Tasks complete</span></div><div><b>${pendingMaterials}</b><span>Material requests</span></div><div><b>${reportCount}</b><span>Daily reports</span></div><div><b>${(state.photos||[]).length}</b><span>Photos</span></div></div><div class="field-command-actions"><button class="btn primary" data-scroll="work">✓ WORK</button><button class="btn" data-scroll="field">✎ UPDATE</button><button class="btn" id="quickMaterial">NEED MATERIAL</button><button class="btn" id="quickPhoto">PHOTO</button></div>${openTasks.length?`<div class="field-next"><b>Next up</b>${openTasks.slice(0,3).map(t=>`<div class="field-next-task"><span>□</span><span>${esc(t.title)}</span></div>`).join("")}${openTasks.length>3?`<div class="sub">+ ${openTasks.length-3} more open task${openTasks.length-3===1?"":"s"}</div>`:""}</div>`:`<div class="field-next complete"><b>✓ All assigned tasks complete</b><div class="sub">Review the job, add a final report, and finish up.</div></div>`}</section>`:"";\n const timePanel=fieldUser?`<div class="card" style="margin:12px 0"><div class="row"><div><b>Time</b>'''
rep(needle,insert,'field command')
# 3 insert fieldCommand in return
rep(' ${financial}${schedulePanel}${changeOrderPanel}${invoicePanel}\n ${timePanel}',' ${financial}${schedulePanel}${changeOrderPanel}${invoicePanel}\n ${fieldCommand}${timePanel}','field command placement')
# 4 task header
old=' const taskHeader=fieldUser?`<div id="section-work" class="job-section"><h3>My Tasks</h3>`:`<div id="section-work" class="job-section"><h3>Tasks <button id="addTask" class="btn" style="float:right">+ Task</button></h3>`;'
new=' const taskHeader=fieldUser?`<div id="section-work" class="job-section"><div class="work-header"><div><div class="eyebrow">WORK</div><h3>My Tasks</h3></div><div class="work-progress"><b>${doneTasks}/${tasks.length}</b><span>${taskPct}% complete</span></div></div><div class="field-progress work-progress-bar"><span style="width:${taskPct}%"></span></div>`:`<div id="section-work" class="job-section"><div class="work-header"><div><div class="eyebrow">WORK</div><h3>Tasks <button id="addTask" class="btn" style="float:right">+ Task</button></h3></div><div class="work-progress"><b>${doneTasks}/${tasks.length}</b><span>${taskPct}% complete</span></div></div><div class="field-progress work-progress-bar"><span style="width:${taskPct}%"></span></div>`;'
rep(old,new,'task header')
# 5 task class
rep('<div class="job" style="margin-bottom:8px"><label style="display:block"><input type="checkbox" data-task="${t.id}" ${t.status==="complete"?"checked":""}> ${esc(t.title)}</label>','<div class="job task-card ${t.status==="complete"?"task-complete":""}" style="margin-bottom:8px"><label style="display:block"><input type="checkbox" data-task="${t.id}" ${t.status==="complete"?"checked":""}> ${esc(t.title)}</label>','task class')
# 6 quick photo + scroll
rep("if(e.target.id==='addPhoto'||e.target.id==='addPhoto2'){if(state.selected)photoPicker();return}","if(e.target.id==='addPhoto'||e.target.id==='addPhoto2'||e.target.id==='quickPhoto'){if(state.selected)photoPicker();return}",'quick photo')
rep('const scroll=e.target.closest("[data-scroll]");if(scroll){const target=document.getElementById("section-field");if(target)target.scrollIntoView({behavior:"smooth",block:"start"});return;}','const scroll=e.target.closest("[data-scroll]");if(scroll){const key=scroll.dataset.scroll||"field";const target=document.getElementById("section-"+key)||document.getElementById("section-field");if(target)target.scrollIntoView({behavior:"smooth",block:"start"});return;}','scroll')
# 7 helper
marker='function photoPicker(){'
rep(marker,'async function logJobActivity(jobId,event_type,message){try{await sb.from("job_activity").insert({job_id:jobId,profile_id:session.user.id,event_type,message});}catch(_){}}\n'+marker,'helper')
# 8 daily report
old="if(e.target.id==='addReport'){if(state.selected)modalForm('Daily Job Report',`<form class=\"form\"><input name=\"report_date\" type=\"date\" value=\"${new Date().toISOString().slice(0,10)}\"><input name=\"hours\" type=\"number\" step=\".25\" placeholder=\"Hours worked\"><textarea name=\"notes\" required placeholder=\"Progress, crew, issues, next steps...\"></textarea><button class=\"btn primary\" type=\"submit\">Save Report</button></form>`,async f=>sb.from('daily_reports').insert({job_id:state.selected.id,submitted_by:session.user.id,report_date:f.get('report_date'),hours:Number(f.get('hours')||0),notes:f.get('notes')}));return}"
new="if(e.target.id==='addReport'){if(state.selected)modalForm('Daily Job Report',`<form class=\"form\"><input name=\"report_date\" type=\"date\" value=\"${new Date().toISOString().slice(0,10)}\"><input name=\"hours\" type=\"number\" step=\".25\" placeholder=\"Hours worked\"><textarea name=\"notes\" required placeholder=\"What was completed today?\nCrew on site:\nIssues / blockers:\nMaterials needed:\nNext steps:\"></textarea><button class=\"btn primary\" type=\"submit\">Save Report</button></form>`,async f=>{const r=await sb.from('daily_reports').insert({job_id:state.selected.id,submitted_by:session.user.id,report_date:f.get('report_date'),hours:Number(f.get('hours')||0),notes:f.get('notes')});if(!r.error)await logJobActivity(state.selected.id,'daily_report','Daily report added.');return r});return}"
rep(old,new,'daily report')
# 9 material handler
old="if(e.target.id===\"addMaterial\"||e.target.id===\"quickMaterial\"){if(!state.selected){toast(\"Open a job first.\");return}modalForm(\"Material Request\",`<form class=\"form\"><input name=\"item\" required placeholder=\"Material\"><input name=\"quantity\" type=\"number\" step=\".01\" value=\"1\"><textarea name=\"notes\" placeholder=\"Notes\"></textarea><button class=\"btn primary\" type=\"submit\">Request Material</button></form>`,async f=>sb.from(\"material_requests\").insert({job_id:state.selected.id,requested_by:session.user.id,item:f.get(\"item\"),quantity:Number(f.get(\"quantity\")||1),notes:f.get(\"notes\")}));return}"
new="if(e.target.id===\"addMaterial\"||e.target.id===\"quickMaterial\"){if(!state.selected){toast(\"Open a job first.\");return}modalForm(\"Material Request\",`<form class=\"form\"><input name=\"item\" required placeholder=\"Material\"><input name=\"quantity\" type=\"number\" step=\".01\" value=\"1\"><textarea name=\"notes\" placeholder=\"Notes\"></textarea><button class=\"btn primary\" type=\"submit\">Request Material</button></form>`,async f=>{const r=await sb.from(\"material_requests\").insert({job_id:state.selected.id,requested_by:session.user.id,item:f.get(\"item\"),quantity:Number(f.get(\"quantity\")||1),notes:f.get(\"notes\")});if(!r.error)await logJobActivity(state.selected.id,'material_request',`Material requested: ${f.get('item')}.`);return r});return}"
rep(old,new,'material handler')
# 10 task activity
rep('if(id){const r=await sb.from("job_tasks").update({status:e.target.checked?"complete":"open",completed_at:e.target.checked?new Date().toISOString():null}).eq("id",id);if(r.error)toast(r.error.message);await load();return}','if(id){const checked=e.target.checked;const r=await sb.from("job_tasks").update({status:checked?"complete":"open",completed_at:checked?new Date().toISOString():null}).eq("id",id);if(r.error)toast(r.error.message);else{const t=state.tasks.find(x=>x.id===id);await logJobActivity(state.selected?.id,"task_update",`${checked?"Completed":"Reopened"} task: ${t?.title||"Task"}.`);}await load();return}','task activity')
# 11 time handlers exact
rep('if(e.target.id==="startJob"){if(!state.selected)return;const existing=state.timeEntries.find(x=>x.profile_id===session.user.id&&!x.ended_at);if(existing){toast("You already have a job running.");return}const r=await sb.from("time_entries").insert({job_id:state.selected.id,profile_id:session.user.id,started_at:new Date().toISOString()}).select().single();if(r.error)toast(r.error.message);else await load();return}','if(e.target.id==="startJob"){if(!state.selected)return;const existing=state.timeEntries.find(x=>x.profile_id===session.user.id&&!x.ended_at);if(existing){toast("You already have a job running.");return}const r=await sb.from("time_entries").insert({job_id:state.selected.id,profile_id:session.user.id,started_at:new Date().toISOString()}).select().single();if(r.error)toast(r.error.message);else{await logJobActivity(state.selected.id,"time_entry","Started job timer.");await load();}return}','start')
rep('if(e.target.id==="stopJob"){if(!state.selected)return;const active=state.timeEntries.find(x=>x.profile_id===session.user.id&&!x.ended_at);if(!active){toast("No active timer for this job.");return}const ended=new Date(); const mins=Math.max(1,Math.round((ended-new Date(active.started_at))/60000)); const r=await sb.from("time_entries").update({ended_at:ended.toISOString(),duration_minutes:mins}).eq("id",active.id);if(r.error)toast(r.error.message);else await load();return}','if(e.target.id==="stopJob"){if(!state.selected)return;const active=state.timeEntries.find(x=>x.profile_id===session.user.id&&!x.ended_at);if(!active){toast("No active timer for this job.");return}const ended=new Date(); const mins=Math.max(1,Math.round((ended-new Date(active.started_at))/60000)); const r=await sb.from("time_entries").update({ended_at:ended.toISOString(),duration_minutes:mins}).eq("id",active.id);if(r.error)toast(r.error.message);else{await logJobActivity(state.selected.id,"time_entry",`Stopped timer after ${(mins/60).toFixed(2)} hours.`);await load();}return}','stop')
rep('if(e.target.id==="logHours"){if(!state.selected)return;modalForm("Log Hours",`<form class="form"><input name="hours" type="number" min="0.01" step="0.25" placeholder="Hours worked" required><textarea name="notes" placeholder="What was completed?"></textarea><button class="btn primary" type="submit">Save Hours</button></form>`,async f=>{const hours=Number(f.get("hours")||0);const now=new Date().toISOString();return sb.from("time_entries").insert({job_id:state.selected.id,profile_id:session.user.id,started_at:now,ended_at:now,duration_minutes:Math.round(hours*60),notes:f.get("notes")})});return}','if(e.target.id==="logHours"){if(!state.selected)return;modalForm("Log Hours",`<form class="form"><input name="hours" type="number" min="0.01" step="0.25" placeholder="Hours worked" required><textarea name="notes" placeholder="What was completed?"></textarea><button class="btn primary" type="submit">Save Hours</button></form>`,async f=>{const hours=Number(f.get("hours")||0);const now=new Date().toISOString();const r=await sb.from("time_entries").insert({job_id:state.selected.id,profile_id:session.user.id,started_at:now,ended_at:now,duration_minutes:Math.round(hours*60),notes:f.get("notes")});if(!r.error)await logJobActivity(state.selected.id,"time_entry",`Logged ${hours.toFixed(2)} hours.`);return r});return}','log hours')
# 12 photo activity
rep("const r=await sb.from('job_photos').insert({job_id:state.selected.id,uploaded_by:session.user.id,storage_path:path,caption:e.target.caption.value});if(r.error){toast(r.error.message);return}wrap.remove();await load();toast('Photo uploaded.')","const r=await sb.from('job_photos').insert({job_id:state.selected.id,uploaded_by:session.user.id,storage_path:path,caption:e.target.caption.value});if(r.error){toast(r.error.message);return}await logJobActivity(state.selected.id,'photo_added',`Job photo added${e.target.caption.value?`: ${e.target.caption.value}`:'.'}`);wrap.remove();await load();toast('Photo uploaded.')",'photo activity')
(root/'app-v62.js').write_text(s)
css=(root/'styles-v61.css').read_text()+'''\n/* V62 Field Command / Work UI */\n.field-command{margin:12px 0;padding:18px;border:2px solid #111;background:#fff;}\n.field-command .eyebrow{margin-bottom:5px;}\n.field-percent{font-size:28px;font-weight:900;}\n.field-progress{height:10px;background:#e7e7e7;border-radius:999px;overflow:hidden;margin:12px 0;}\n.field-progress span{display:block;height:100%;background:#ffe500;min-width:0;}\n.field-command-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin:14px 0;}\n.field-command-grid>div{border:1px solid #ddd;border-radius:12px;padding:10px;background:#f7f7f7;}\n.field-command-grid b,.field-command-grid span{display:block;}\n.field-command-grid b{font-size:22px;}\n.field-command-grid span{font-size:12px;color:#666;margin-top:2px;}\n.field-command-actions{display:flex;gap:8px;flex-wrap:wrap;}\n.field-next{margin-top:14px;padding-top:12px;border-top:1px solid #ddd;}\n.field-next-task{display:flex;gap:8px;align-items:center;padding:8px 0;font-weight:700;}\n.field-next.complete{padding:12px;border-radius:12px;background:#f3f3f3;}\n.work-header{display:flex;justify-content:space-between;align-items:flex-end;gap:12px;margin-bottom:6px;}\n.work-header h3{margin:0;}\n.work-progress{text-align:right;}\n.work-progress b,.work-progress span{display:block;}\n.work-progress b{font-size:20px;}\n.work-progress span{font-size:12px;color:#666;}\n.work-progress-bar{margin:8px 0 12px;}\n.task-card.task-complete{opacity:.72;}\n.task-card.task-complete label{text-decoration:line-through;}\n@media(max-width:640px){.field-command-grid{grid-template-columns:repeat(2,1fr)}.field-command-actions .btn{flex:1 1 calc(50% - 8px);min-height:44px}.work-header{align-items:flex-start}.job-tabs{overflow-x:auto;flex-wrap:nowrap}.job-tab{white-space:nowrap;flex:0 0 auto}}\n'''
(root/'styles-v62.css').write_text(css)
idx=(root/'index.html').read_text().replace('styles-v61.css','styles-v62.css').replace('app-v61.js','app-v62.js')
(root/'index.html').write_text(idx)
(root/'V62_NOTES.txt').write_text('''Nolan Electric Job Command Center V62\n\nBuilt from the verified V61 foundation.\n\nField/Work upgrade:\n- Field Command brief at top of field job view.\n- Task completion progress, material/report/photo counts and Next Up list.\n- Quick Work, Update, Need Material and Photo actions.\n- Functional Schedule tab.\n- Work progress bar for field/admin.\n- Visual completed task state.\n- Activity logging for task changes, reports, material requests, photos and time entries.\n- Expanded daily report prompts for completed work, crew, blockers, materials and next steps.\n- Fixed job top-level invoice/paid totals to use the actual invoice total field.\n- Existing config.js remains separate; no service worker added.\n\nValidation: Node syntax check passed before packaging.\n''')
